#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app.swagger_ui:
    path: /api/docs
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# config/routes.yaml
app.swagger:
    path: /api/docs.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

# config/routes.yaml
api_login_check:
    path: /api/login_check
